# EPIC 2 - Melbourne Street Furniture and Services
This Jupyter Notebook is about preparing 'Melbourne Street Furniture and Services' CSV file for being used in Mo-Buddy Website Solution.
1. Read Raw Data
2. Clean Raw Data
3. Export Clean Data

In [123]:
# Import Packages
import pandas as pd

In [124]:
# Set option to display all columns
pd.set_option('display.max_columns', None)

## 1. Read in Raw Data from a CSV file

In [125]:
# Function for reading in raw data from a CSV file
def read_in_data(file_path):
    """
    Function for reading in raw data from CSV file.
    Inputs: 
        - file_Path, type: string, desc: CSV file path
    Outputs:
        - raw_data, type: dataframe, desc: Raw data
    """

    raw_data = pd.read_csv(file_path)
    
    return raw_data

In [126]:
# Read in data
filepath_raw_data = 'DataBases\Melbourne_Street_Furniture.csv'
df_raw_furniture = read_in_data(filepath_raw_data)

In [127]:
df_raw_furniture.head()

,GIS_ID,DESCRIPTION,ASSET_CLASS,ASSET_TYPE,MODEL_NO,MODEL_DESCR,DIVISION,COMPANY,LOCATION_DESC,CONDITION_RATING,EVALUATION_DATE,EASTING,NORTHING,UploadDate,CoordinateLocation
0,1075493,Litter Bin - Steel 80 L Litter Bin,Outdoor Furniture,Litter Bin,200201-016,Litter Bin - Steel 80 L Litter Bin,Waste and Recycling,City of Melbourne,King Street between Bourke Street and Little B...,3.12,30/04/2021,320047.29,5812660.15,14/08/2021,"(-37.81573650863262, 144.95557617927093)"
1,1075947,Litter Bin - Stainless Steel 80 L Litter Bin,Outdoor Furniture,Litter Bin,200201-011,Litter Bin - Stainless Steel 80 L Litter Bin,Waste and Recycling,City of Melbourne,Queensberry Street between Errol Street and Cu...,3.43,30/04/2021,319378.09,5814081.45,14/08/2021,"(-37.80280211887129, 144.94833234426707)"
2,1075949,Litter Bin - Stainless Steel 80 L Litter Bin,Outdoor Furniture,Litter Bin,200201-011,Litter Bin - Stainless Steel 80 L Litter Bin,Waste and Recycling,City of Melbourne,Queensberry Street between Leveson Street and ...,3.43,30/04/2021,319511.06,5814066.21,14/08/2021,"(-37.80296568173825, 144.9498380533202)"
3,1075950,Litter Bin - Stainless Steel 80 L Litter Bin,Outdoor Furniture,Litter Bin,200201-011,Litter Bin - Stainless Steel 80 L Litter Bin,Waste and Recycling,City of Melbourne,Queensberry Street between Errol Street and Cu...,3.43,30/04/2021,319470.86,5814046.58,14/08/2021,"(-37.80313455126292, 144.94937680211217)"
4,1075951,Litter Bin - Steel 80 L Litter Bin,Outdoor Furniture,Litter Bin,200201-016,Litter Bin - Steel 80 L Litter Bin,Waste and Recycling,City of Melbourne,Queensberry Street between Leveson Street and ...,3.14,30/04/2021,319507.61,5814042.04,14/08/2021,"(-37.80318270915577, 144.94979286737458)"

## 2. Clean up Raw Data

In [128]:
# Check furniture according to ASSET_TYPE
df_raw_furniture['ASSET_TYPE'].value_counts()

Bollard                     9388
Bicycle Rails               5900
Seat                        3389
Litter Bin                  3294
Tree Guard                   450
Drinking Fountain            302
Floral Crate/Planter Box     206
Hoop                         202
Picnic Setting               170
Barbeque                      63
Information Pillar            43
Horse Trough                  19
Name: ASSET_TYPE, dtype: int64

In [129]:
# Select only furniture that is atractive for users. (Seat, Litter Bin, Drinking Fountain, Picnic Setting, Barbeque)
atractive_furniture = ['Picnic Setting', 'Barbeque']
df_furniture = df_raw_furniture[df_raw_furniture['ASSET_TYPE'].isin(atractive_furniture)]
df_furniture.head()

,GIS_ID,DESCRIPTION,ASSET_CLASS,ASSET_TYPE,MODEL_NO,MODEL_DESCR,DIVISION,COMPANY,LOCATION_DESC,CONDITION_RATING,EVALUATION_DATE,EASTING,NORTHING,UploadDate,CoordinateLocation
3939,1110846,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,201201-001,Barbeque - Urban Design Single Hotplate,Parks and City Greening,City of Melbourne,Princes Park,2.0,10/09/2019,320558.43,5816079.32,14/08/2021,"(-37.785038996971224, 144.96222644314096)"
3940,1110847,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,201201-001,Barbeque - Urban Design Single Hotplate,Parks and City Greening,City of Melbourne,Princes Park,3.0,10/09/2019,320576.36,5816075.58,14/08/2021,"(-37.78507620578955, 144.96242901615196)"
3941,1110848,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,201201-001,Barbeque - Urban Design Single Hotplate,Parks and City Greening,City of Melbourne,Royal Park,3.0,09/09/2019,319745.86,5815864.77,14/08/2021,"(-37.786811624350314, 144.95295080957254)"
3942,1110849,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,201201-001,Barbeque - Urban Design Single Hotplate,Parks and City Greening,City of Melbourne,Bayswater Road Park approximately 41m South of...,3.0,16/09/2019,317216.98,5815038.47,14/08/2021,"(-37.79375198566206, 144.92404057125708)"
3943,1110855,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,201201-001,Barbeque - Urban Design Single Hotplate,Parks and City Greening,City of Melbourne,Birrarung Marr,4.0,22/08/2019,321749.55,5812243.74,14/08/2021,"(-37.819821342236914, 144.97480170753713)"

In [130]:
# Check whether the dataframe is as expected
df_furniture['ASSET_TYPE'].value_counts()

Picnic Setting    170
Barbeque           63
Name: ASSET_TYPE, dtype: int64

In [131]:
# Selet only usefull columns
useful_column = ['GIS_ID', 'DESCRIPTION', 'ASSET_CLASS', 'ASSET_TYPE', 'DIVISION',
                'LOCATION_DESC', 'CoordinateLocation']
df_furniture = df_furniture.loc[:,useful_column]

In [132]:
# Check whether the dataframe is as expected
df_furniture.head()

,GIS_ID,DESCRIPTION,ASSET_CLASS,ASSET_TYPE,DIVISION,LOCATION_DESC,CoordinateLocation
3939,1110846,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Princes Park,"(-37.785038996971224, 144.96222644314096)"
3940,1110847,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Princes Park,"(-37.78507620578955, 144.96242901615196)"
3941,1110848,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Royal Park,"(-37.786811624350314, 144.95295080957254)"
3942,1110849,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Bayswater Road Park approximately 41m South of...,"(-37.79375198566206, 144.92404057125708)"
3943,1110855,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Birrarung Marr,"(-37.819821342236914, 144.97480170753713)"

In [133]:
# Check missing values
df_furniture.isnull().sum()

GIS_ID                0
DESCRIPTION           0
ASSET_CLASS           0
ASSET_TYPE            0
DIVISION              0
LOCATION_DESC         0
CoordinateLocation    0
dtype: int64

In [134]:
df_furniture[df_furniture['DIVISION'].isnull()]

Empty DataFrame
Columns: [GIS_ID, DESCRIPTION, ASSET_CLASS, ASSET_TYPE, DIVISION, LOCATION_DESC, CoordinateLocation]
Index: []

In [135]:
# split 'CoordinateLocation' -> 'latitude' 'longitude'
long_lati = df_furniture['CoordinateLocation'].str.extract(r'\((.*)\)')[0].str.split(',')
df_furniture.insert(7, 'latitude', long_lati.str[0])
df_furniture.insert(8, 'longitude', long_lati.str[1])

In [136]:
# Check whether the dataframe is as expected
df_furniture.head()

,GIS_ID,DESCRIPTION,ASSET_CLASS,ASSET_TYPE,DIVISION,LOCATION_DESC,CoordinateLocation,latitude,longitude
3939,1110846,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Princes Park,"(-37.785038996971224, 144.96222644314096)",-37.785038996971224,144.96222644314096
3940,1110847,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Princes Park,"(-37.78507620578955, 144.96242901615196)",-37.78507620578955,144.96242901615196
3941,1110848,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Royal Park,"(-37.786811624350314, 144.95295080957254)",-37.786811624350314,144.95295080957254
3942,1110849,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Bayswater Road Park approximately 41m South of...,"(-37.79375198566206, 144.92404057125708)",-37.79375198566206,144.92404057125708
3943,1110855,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Parks and City Greening,Birrarung Marr,"(-37.819821342236914, 144.97480170753713)",-37.819821342236914,144.97480170753713

In [137]:
# Get usefull coluns
usefull_columns = [0, 1, 2, 3, 5, 7, 8]
df_furniture = df_furniture.iloc[:, usefull_columns].copy()

In [138]:
# Check whether the dataframe is as expected
df_furniture.head()

,GIS_ID,DESCRIPTION,ASSET_CLASS,ASSET_TYPE,LOCATION_DESC,latitude,longitude
3939,1110846,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Princes Park,-37.785038996971224,144.96222644314096
3940,1110847,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Princes Park,-37.78507620578955,144.96242901615196
3941,1110848,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Royal Park,-37.786811624350314,144.95295080957254
3942,1110849,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Bayswater Road Park approximately 41m South of...,-37.79375198566206,144.92404057125708
3943,1110855,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Birrarung Marr,-37.819821342236914,144.97480170753713

In [139]:
# Rename columns accordingly with format
df_furniture.rename(columns={'GIS_ID':'id', 'DESCRIPTION':'description', 
                             'ASSET_CLASS':'class', 'ASSET_TYPE':'type', 
                             'LOCATION_DESC':'location1'}, inplace=True)

In [140]:
# Check whether the dataframe is as expected
df_furniture.head()

,id,description,class,type,location1,latitude,longitude
3939,1110846,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Princes Park,-37.785038996971224,144.96222644314096
3940,1110847,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Princes Park,-37.78507620578955,144.96242901615196
3941,1110848,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Royal Park,-37.786811624350314,144.95295080957254
3942,1110849,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Bayswater Road Park approximately 41m South of...,-37.79375198566206,144.92404057125708
3943,1110855,Barbeque - Urban Design Single Hotplate,Outdoor Furniture,Barbeque,Birrarung Marr,-37.819821342236914,144.97480170753713

In [141]:
# split 'address' -> 'address' 'reference'
add_ref = df_furniture['location1'].str.split(' between ')
df_furniture.insert(2, 'location', add_ref.str[0])
df_furniture.insert(3, 'reference', add_ref.str[1])

In [142]:
# Check whether the dataframe is as expected
df_furniture.head()

,id,description,location,reference,class,type,location1,latitude,longitude
3939,1110846,Barbeque - Urban Design Single Hotplate,Princes Park,NaN,Outdoor Furniture,Barbeque,Princes Park,-37.785038996971224,144.96222644314096
3940,1110847,Barbeque - Urban Design Single Hotplate,Princes Park,NaN,Outdoor Furniture,Barbeque,Princes Park,-37.78507620578955,144.96242901615196
3941,1110848,Barbeque - Urban Design Single Hotplate,Royal Park,NaN,Outdoor Furniture,Barbeque,Royal Park,-37.786811624350314,144.95295080957254
3942,1110849,Barbeque - Urban Design Single Hotplate,Bayswater Road Park approximately 41m South of...,NaN,Outdoor Furniture,Barbeque,Bayswater Road Park approximately 41m South of...,-37.79375198566206,144.92404057125708
3943,1110855,Barbeque - Urban Design Single Hotplate,Birrarung Marr,NaN,Outdoor Furniture,Barbeque,Birrarung Marr,-37.819821342236914,144.97480170753713

In [143]:
# Check missing values
df_furniture.isnull().sum()

id               0
description      0
location         0
reference      230
class            0
type             0
location1        0
latitude         0
longitude        0
dtype: int64

In [144]:
null_ref = df_furniture['reference'].isnull()
df_furniture[null_ref]

,id,description,location,reference,class,type,location1,latitude,longitude
3939,1110846,Barbeque - Urban Design Single Hotplate,Princes Park,NaN,Outdoor Furniture,Barbeque,Princes Park,-37.785038996971224,144.96222644314096
3940,1110847,Barbeque - Urban Design Single Hotplate,Princes Park,NaN,Outdoor Furniture,Barbeque,Princes Park,-37.78507620578955,144.96242901615196
3941,1110848,Barbeque - Urban Design Single Hotplate,Royal Park,NaN,Outdoor Furniture,Barbeque,Royal Park,-37.786811624350314,144.95295080957254
3942,1110849,Barbeque - Urban Design Single Hotplate,Bayswater Road Park approximately 41m South of...,NaN,Outdoor Furniture,Barbeque,Bayswater Road Park approximately 41m South of...,-37.79375198566206,144.92404057125708
3943,1110855,Barbeque - Urban Design Single Hotplate,Birrarung Marr,NaN,Outdoor Furniture,Barbeque,Birrarung Marr,-37.819821342236914,144.97480170753713
...,...,...,...,...,...,...,...,...,...
23408,1800418,Barbeque - All Abilities Double Hotplate - Roy...,"Royal Park approximately 83m NE of Tenancy 4, ...",NaN,Outdoor Furniture,Barbeque,"Royal Park approximately 83m NE of Tenancy 4, ...",-37.79505799178623,144.95104163931634
23418,1806221,Barbeque - Urban Design Single Hotplate - Sout...,Intersection of Southbank Boulevard and Moore ...,NaN,Outdoor Furniture,Barbeque,Intersection of Southbank Boulevard and Moore ...,-37.82345728026392,144.96617846018844
23423,1806222,Barbeque - Urban Design Single Hotplate - Sout...,Intersection of Southbank Boulevard and Moore ...,NaN,Outdoor Furniture,Barbeque,Intersection of Southbank Boulevard and Moore ...,-37.82337894328665,144.96620310536593
23424,1806223,Picnic Setting - Urban Design Style - Southban...,Intersection of Southbank Boulevard and Moore ...,NaN,Outdoor Furniture,Picnic Setting,Intersection of Southbank Boulevard and Moore ...,-37.82343713897669,144.96618628410965
23425,1806224,Picnic Setting - Urban Design Style - Southban...,Intersection of Southbank Boulevard and Moore ...,NaN,Outdoor Furniture,Picnic Setting,Intersection of Southbank Boulevard and Moore ...,-37.823396766169495,144.96619670841014

In [145]:
# split 'address' -> 'address' 'reference'
add_ref = df_furniture.loc[null_ref,'location1'].str.split(' approximately ')
df_furniture.loc[null_ref, 'location'] = add_ref.str[0]
df_furniture.loc[null_ref, 'reference'] = add_ref.str[1]

In [146]:
# Check missing values
df_furniture.isnull().sum()

id              0
description     0
location        0
reference      92
class           0
type            0
location1       0
latitude        0
longitude       0
dtype: int64

In [147]:
null_ref = df_furniture['reference'].isnull()
df_furniture[null_ref]

,id,description,location,reference,class,type,location1,latitude,longitude
3939,1110846,Barbeque - Urban Design Single Hotplate,Princes Park,NaN,Outdoor Furniture,Barbeque,Princes Park,-37.785038996971224,144.96222644314096
3940,1110847,Barbeque - Urban Design Single Hotplate,Princes Park,NaN,Outdoor Furniture,Barbeque,Princes Park,-37.78507620578955,144.96242901615196
3941,1110848,Barbeque - Urban Design Single Hotplate,Royal Park,NaN,Outdoor Furniture,Barbeque,Royal Park,-37.786811624350314,144.95295080957254
3943,1110855,Barbeque - Urban Design Single Hotplate,Birrarung Marr,NaN,Outdoor Furniture,Barbeque,Birrarung Marr,-37.819821342236914,144.97480170753713
3944,1110856,Barbeque - Urban Design Single Hotplate,Birrarung Marr,NaN,Outdoor Furniture,Barbeque,Birrarung Marr,-37.82009381572264,144.97510314880833
...,...,...,...,...,...,...,...,...,...
23004,1742342,Barbeque - Urban Design Single Hotplate - Hawk...,Hawke & Adderley Street Park,NaN,Outdoor Furniture,Barbeque,Hawke & Adderley Street Park,-37.808803420080686,144.9450258108489
23109,1755053,Picnic Setting - Urban Design Style - Gardiner...,Gardiner Reserve,NaN,Outdoor Furniture,Picnic Setting,Gardiner Reserve,-37.79952597865392,144.94376962251957
23141,1764812,Picnic Setting - Urban Design Style - Wharfs L...,Wharfs Landing,NaN,Outdoor Furniture,Picnic Setting,Wharfs Landing,-37.822046979543856,144.93668403481513
23147,1768645,Picnic Setting - Urban Design Style - Alexandr...,Alexandra Park,NaN,Outdoor Furniture,Picnic Setting,Alexandra Park,-37.827822960307756,144.9831322017755
23152,1764805,Barbeque - Docklands Barbeque - All Chromed - ...,Wharfs Landing,NaN,Outdoor Furniture,Barbeque,Wharfs Landing,-37.82197015645569,144.93671241740378

In [148]:
# copy 'location' -> 'reference'
df_furniture.loc[null_ref, 'reference'] = df_furniture.loc[null_ref, 'location']

In [149]:
# Check missing values
df_furniture.isnull().sum()

id             0
description    0
location       0
reference      0
class          0
type           0
location1      0
latitude       0
longitude      0
dtype: int64

In [150]:
usefull_col = [0, 4, 5, 2, 3, 7 ,8]
df_furniture = df_furniture.iloc[:, usefull_col]
df_furniture

,id,class,type,location,reference,latitude,longitude
3939,1110846,Outdoor Furniture,Barbeque,Princes Park,Princes Park,-37.785038996971224,144.96222644314096
3940,1110847,Outdoor Furniture,Barbeque,Princes Park,Princes Park,-37.78507620578955,144.96242901615196
3941,1110848,Outdoor Furniture,Barbeque,Royal Park,Royal Park,-37.786811624350314,144.95295080957254
3942,1110849,Outdoor Furniture,Barbeque,Bayswater Road Park,"41m South of 39 Bayswater Road, Kensington, 3031",-37.79375198566206,144.92404057125708
3943,1110855,Outdoor Furniture,Barbeque,Birrarung Marr,Birrarung Marr,-37.819821342236914,144.97480170753713
...,...,...,...,...,...,...,...
23408,1800418,Outdoor Furniture,Barbeque,Royal Park,"83m NE of Tenancy 4, Ground, 48 Flemington Roa...",-37.79505799178623,144.95104163931634
23418,1806221,Outdoor Furniture,Barbeque,Intersection of Southbank Boulevard and Moore ...,"57m South of Kimi's, Ground, 20 Kavanagh Stree...",-37.82345728026392,144.96617846018844
23423,1806222,Outdoor Furniture,Barbeque,Intersection of Southbank Boulevard and Moore ...,"49m South of Kimi's, Ground, 20 Kavanagh Stree...",-37.82337894328665,144.96620310536593
23424,1806223,Outdoor Furniture,Picnic Setting,Intersection of Southbank Boulevard and Moore ...,"55m South of Kimi's, Ground, 20 Kavanagh Stree...",-37.82343713897669,144.96618628410965
23425,1806224,Outdoor Furniture,Picnic Setting,Intersection of Southbank Boulevard and Moore ...,"51m South of Kimi's, Ground, 20 Kavanagh Stree...",-37.823396766169495,144.96619670841014

## 3. Export Clean Data to a CSV file

In [151]:
# Export full version
df_furniture.to_csv('Output\Furniture\OK_Public_Furniture_Melbourne_V3.csv', index=False)