# EPIC 4 - Become a Carer - T35.1 - Primary Carer, Place Recipient Live, Age
This Jupyter Notebook is about preparing 'Number of primary carers, by age and sex, 2018' XLS file for being used in Mo-Buddy Website Solution.
1. Read Raw Data
2. Clean Raw Data
3. Export Clean Data

- Table_29.1 - Carer status by sex, age
- Table_30.1 - Carer status, recipient, disability status, age, sex
- Table_31.1 - Carer status, by geographic location, age, sex
- Table_32.1 - 15-.. yo, carer status, sex 
- Table_33.1 - Employed 15-64 yo, carer status, sex 
- Table_34.1 - Primary Carer, recipient, age, sex
- Table_35.1 - Carer and recipient living in or other households, age
- Table_36.1 - Primary Carer, Time spending in care, sex  ****
- Table_37.1 - Primary Carer, age, time spending in care, disability status, ***** 
- Table_38.1 - Primary Carer, time spending in care, select recipint   ****
- Table_39.1 - Primary Carer, reason for taking a carer, sex   ****
- Table_40.1 - Primary Carer, reason for taking a carer, age of recipient ****
- Table_41.1 - Primary Carer, satisfaction of service recieved, sex, age  ****
- Table_42.1 - Primary Carer, social community participation with recipient, time spending in car, age  ****
- Table_43.1 - Primary Carer, social community participation without recipient, time spending in car, age  ****

In [1]:
# Import Packages
import pandas as pd
import itertools
# import re

In [2]:
# Set option to display all columns
pd.set_option('display.max_columns', None)

## 1. Read in Raw Data from a XLS file

In [3]:
# Function for reading in raw data from a XLS file
def read_in_data(file_path, sheet_name):
    """
    Function for reading in raw data from XLS file.
    Inputs: 
        - file_path, type: string, desc: XLS file path
        - sheet_name, type: string, desc: Sheet Name
    Outputs:
        - raw_data, type: dataframe, desc: Raw data
    """

    raw_data = pd.read_excel(io=file_path, sheet_name=sheet_name)
    
    return raw_data

In [4]:
# Read in data
filepath_raw_data = 'DataBases/44300do030.xls'
sheet_name = 'Table_35.1'
df_raw_carer_35 = read_in_data(filepath_raw_data, sheet_name)

In [5]:
# Check how the dataframe looks like
df_raw_carer_35

,Australian Bureau of Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,"44300DO030_2018 Disability, Ageing and Carers,...",NaN,NaN,NaN
1,Released at 11.30am (Canberra time) Thurs 24 O...,NaN,NaN,NaN
2,"Table 35.1 Primary carers, whether main recipi...",NaN,NaN,NaN
3,Age group of primary carer,Main recipient of care lives in same household,Main recipient of care lives elsewhere,Total
4,ESTIMATE ('000),NaN,NaN,NaN
5,Partner of recipient,NaN,NaN,NaN
6,15–24 years,1.3,0,1.3
7,25–44 years,32,0,32
8,45–64 years,109.3,0,111.4
9,65 years and over,169.5,4,172.8
10,Total,310.4,3.6,315.2
11,NaN,NaN,NaN,NaN
12,Child of recipient,NaN,NaN,NaN
13,15–24 years,6.1,0,7.8
14,25–44 years,27,20.5,48.6
15,45–64 years,59.1,86.2,146.6
16,65 years and over,9,11.3,20.3
17,Total,105.6,119.6,226
18,NaN,NaN,NaN,NaN
19,Parent of recipient,NaN,NaN,NaN
20,15–24 years,1.9,0,1.9
21,25–44 years,103.9,0,104
22,45–64 years,95.5,9,102.2
23,65 years and over,14.7,6.8,21.8
24,Total,217.8,16.5,233.5
25,NaN,NaN,NaN,NaN
26,Other relationship to recipient,NaN,NaN,NaN
27,15–24 years,5,5.7,8.1
28,25–44 years,12.2,10.4,20.5
29,45–64 years,26.3,20.3,45.7
30,65 years and over,7.3,5,12.1
31,Total,48.6,40.4,89.6
32,NaN,NaN,NaN,NaN
33,All primary carers,NaN,NaN,NaN
34,15–24 years,16.7,5.1,18.6
35,25–44 years,173.7,30.9,205.6
36,45–64 years,292,115.3,406
37,65 years and over,201.7,29.8,228.3
38,Total,681.4,178.4,861.6
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,© Commonwealth of Australia 2019,NaN,NaN,NaN

## 2. Clean up Raw Data

In [6]:
# Drop useless rows and columns
col_names = df_raw_carer_35.iloc[3,:]
df_carer_35 = df_raw_carer_35.copy()
df_carer_35.drop(labels=[0,1,2,4,5,11,12,18,19,25,26,32,33,39,40,41], axis=0, inplace=True)
df_carer_35.reset_index(drop=True, inplace=True)
df_carer_35.columns = col_names
df_carer_35.rename(columns={'Total':'total'}, inplace=True)
df_carer_35.columns.names = ['']
df_carer_35

,Age group of primary carer,Main recipient of care lives in same household,Main recipient of care lives elsewhere,total
0,Age group of primary carer,Main recipient of care lives in same household,Main recipient of care lives elsewhere,Total
1,15–24 years,1.3,0,1.3
2,25–44 years,32,0,32
3,45–64 years,109.3,0,111.4
4,65 years and over,169.5,4,172.8
5,Total,310.4,3.6,315.2
6,15–24 years,6.1,0,7.8
7,25–44 years,27,20.5,48.6
8,45–64 years,59.1,86.2,146.6
9,65 years and over,9,11.3,20.3
10,Total,105.6,119.6,226
11,15–24 years,1.9,0,1.9
12,25–44 years,103.9,0,104
13,45–64 years,95.5,9,102.2
14,65 years and over,14.7,6.8,21.8
15,Total,217.8,16.5,233.5
16,15–24 years,5,5.7,8.1
17,25–44 years,12.2,10.4,20.5
18,45–64 years,26.3,20.3,45.7
19,65 years and over,7.3,5,12.1
20,Total,48.6,40.4,89.6
21,15–24 years,16.7,5.1,18.6
22,25–44 years,173.7,30.9,205.6
23,45–64 years,292,115.3,406
24,65 years and over,201.7,29.8,228.3
25,Total,681.4,178.4,861.6

In [7]:
# Reset index and prepare for adding multiindex (in column)
df_carer_35.rename(columns={df_carer_35.columns[0]:'Index'}, inplace=True)
df_carer_35.set_index(keys='Index', drop=True, inplace=True)
df_carer_35

,Main recipient of care lives in same household,Main recipient of care lives elsewhere,total
Index,,,
Age group of primary carer,Main recipient of care lives in same household,Main recipient of care lives elsewhere,Total
15–24 years,1.3,0,1.3
25–44 years,32,0,32
45–64 years,109.3,0,111.4
65 years and over,169.5,4,172.8
Total,310.4,3.6,315.2
15–24 years,6.1,0,7.8
25–44 years,27,20.5,48.6
45–64 years,59.1,86.2,146.6
65 years and over,9,11.3,20.3
Total,105.6,119.6,226
15–24 years,1.9,0,1.9
25–44 years,103.9,0,104
45–64 years,95.5,9,102.2
65 years and over,14.7,6.8,21.8
Total,217.8,16.5,233.5
15–24 years,5,5.7,8.1
25–44 years,12.2,10.4,20.5
45–64 years,26.3,20.3,45.7
65 years and over,7.3,5,12.1
Total,48.6,40.4,89.6
15–24 years,16.7,5.1,18.6
25–44 years,173.7,30.9,205.6
45–64 years,292,115.3,406
65 years and over,201.7,29.8,228.3
Total,681.4,178.4,861.6

In [8]:
# Adding multiIndex (in column)
# first_level = ['Average weekly hours spent caring', 'Years of care provided to main recipient of care', 'Total']
# second_level = list(col_names)[1:-1]
# levels_1_1 = list(itertools.product([first_level[0]], second_level[0:3]))
# levels_1_2 = list(itertools.product([first_level[1]], second_level[3:8]))
# levels_1_3 = list(itertools.product([first_level[2]], ['Total']))
# levels = levels_1_1 + levels_1_2 + levels_1_3
# df_carer_36.columns = pd.MultiIndex.from_tuples(levels, names=["Type", "Time"])
df_carer_35.reset_index(inplace=True)
df_carer_35

,Index,Main recipient of care lives in same household,Main recipient of care lives elsewhere,total
0,Age group of primary carer,Main recipient of care lives in same household,Main recipient of care lives elsewhere,Total
1,15–24 years,1.3,0,1.3
2,25–44 years,32,0,32
3,45–64 years,109.3,0,111.4
4,65 years and over,169.5,4,172.8
5,Total,310.4,3.6,315.2
6,15–24 years,6.1,0,7.8
7,25–44 years,27,20.5,48.6
8,45–64 years,59.1,86.2,146.6
9,65 years and over,9,11.3,20.3
10,Total,105.6,119.6,226
11,15–24 years,1.9,0,1.9
12,25–44 years,103.9,0,104
13,45–64 years,95.5,9,102.2
14,65 years and over,14.7,6.8,21.8
15,Total,217.8,16.5,233.5
16,15–24 years,5,5.7,8.1
17,25–44 years,12.2,10.4,20.5
18,45–64 years,26.3,20.3,45.7
19,65 years and over,7.3,5,12.1
20,Total,48.6,40.4,89.6
21,15–24 years,16.7,5.1,18.6
22,25–44 years,173.7,30.9,205.6
23,45–64 years,292,115.3,406
24,65 years and over,201.7,29.8,228.3
25,Total,681.4,178.4,861.6

In [9]:
# Dropping useless rows
df_carer_35_1 =df_carer_35.copy()
df_carer_35_1.drop(labels=[0] , axis=0, inplace=True)
df_carer_35_1.reset_index(drop=True, inplace=True)
df_carer_35_1

,Index,Main recipient of care lives in same household,Main recipient of care lives elsewhere,total
0,15–24 years,1.3,0,1.3
1,25–44 years,32,0,32
2,45–64 years,109.3,0,111.4
3,65 years and over,169.5,4,172.8
4,Total,310.4,3.6,315.2
5,15–24 years,6.1,0,7.8
6,25–44 years,27,20.5,48.6
7,45–64 years,59.1,86.2,146.6
8,65 years and over,9,11.3,20.3
9,Total,105.6,119.6,226
10,15–24 years,1.9,0,1.9
11,25–44 years,103.9,0,104
12,45–64 years,95.5,9,102.2
13,65 years and over,14.7,6.8,21.8
14,Total,217.8,16.5,233.5
15,15–24 years,5,5.7,8.1
16,25–44 years,12.2,10.4,20.5
17,45–64 years,26.3,20.3,45.7
18,65 years and over,7.3,5,12.1
19,Total,48.6,40.4,89.6
20,15–24 years,16.7,5.1,18.6
21,25–44 years,173.7,30.9,205.6
22,45–64 years,292,115.3,406
23,65 years and over,201.7,29.8,228.3
24,Total,681.4,178.4,861.6

In [10]:
levels_names = df_carer_35_1['Index'].unique()
levels_names

array(['15–24 years', '25–44 years', '45–64 years', '65 years and over',
       'Total'], dtype=object)

In [11]:
first_level = ['Partner of recipient', 'Child of recipient', 'Parent of recipient', 
               'Other relationship to recipient', 'All primary carers']
first_level

['Partner of recipient',
 'Child of recipient',
 'Parent of recipient',
 'Other relationship to recipient',
 'All primary carers']

In [12]:
second_level = levels_names
second_level

array(['15–24 years', '25–44 years', '45–64 years', '65 years and over',
       'Total'], dtype=object)

In [13]:
# Adding multiIndex (in index)
levels_all = list(itertools.product(first_level, second_level))
multi_index = pd.MultiIndex.from_tuples(levels_all, names=['Relation', 'Age'])
df_carer_35_1.set_index(keys=multi_index, drop=True, inplace=True)
df_carer_35_1.drop(columns='Index', axis=1, inplace=True)
df_carer_35_1

                                                  Main recipient  of care lives in same household  \
Relation                        Age
Partner of recipient            15–24 years                                                   1.3
                                25–44 years                                                    32
                                45–64 years                                                 109.3
                                65 years and over                                           169.5
                                Total                                                       310.4
Child of recipient              15–24 years                                                   6.1
                                25–44 years                                                    27
                                45–64 years                                                  59.1
                                65 years and over                                               9
                                Total                                                       105.6
Parent of recipient             15–24 years                                                   1.9
                                25–44 years                                                 103.9
                                45–64 years                                                  95.5
                                65 years and over                                            14.7
                                Total                                                       217.8
Other relationship to recipient 15–24 years                                                     5
                                25–44 years                                                  12.2
                                45–64 years                                                  26.3
                                65 years and over                                             7.3
                                Total                                                        48.6
All primary carers              15–24 years                                                  16.7
                                25–44 years                                                 173.7
                                45–64 years                                                   292
                                65 years and over                                           201.7
                                Total                                                       681.4

                                                  Main recipient of care lives elsewhere  \
Relation                        Age
Partner of recipient            15–24 years                                            0
                                25–44 years                                            0
                                45–64 years                                            0
                                65 years and over                                      4
                                Total                                                3.6
Child of recipient              15–24 years                                            0
                                25–44 years                                         20.5
                                45–64 years                                         86.2
                                65 years and over                                   11.3
                                Total                                              119.6
Parent of recipient             15–24 years                                            0
                                25–44 years                                            0
                                45–64 years                                            9
                                65 years and over                                    6.8
                                Total                                               16.5
Other relationship to recipient 15–24 years                                          5.7
                                25–44 years                                         10.4
                                45–64 years                                         20.3
                                65 years and over                                      5
                                Total                                               40.4
All primary carers              15–24 years                                          5.1
                                25–44 years                                         30.9
                                45–64 years                                        115.3
                                65 years and over                                   29.8
                                Total                                              178.4

                                                   total
Relation                        Age
Partner of recipient            15–24 years          1.3
                                25–44 years           32
                                45–64 years        111.4
                                65 years and over  172.8
                                Total              315.2
Child of recipient              15–24 years          7.8
                                25–44 years         48.6
                                45–64 years        146.6
                                65 years and over   20.3
                                Total                226
Parent of recipient             15–24 years          1.9
                                25–44 years          104
                                45–64 years        102.2
                                65 years and over   21.8
                                Total              233.5
Other relationship to recipient 15–24 years          8.1
                                25–44 years         20.5
                                45–64 years         45.7
                                65 years and over   12.1
                                Total               89.6
All primary carers              15–24 years         18.6
                                25–44 years        205.6
                                45–64 years          406
                                65 years and over  228.3
                                Total              861.6

## 3. Export Clean Data to a CSV file

In [14]:
# Export full version
df_carer_35_1.to_csv('Output\EPIC4_T35_1_V1.csv', index=True)