# EPIC 4 - Become a Carer - T34.1 - Primary Carer, Relationship Recipient, Age, Sex
This Jupyter Notebook is about preparing 'Number of primary carers, by age and sex, 2018' XLS file for being used in Mo-Buddy Website Solution.
1. Read Raw Data
2. Clean Raw Data
3. Export Clean Data

- Table_29.1 - Carer status by sex, age
- Table_30.1 - Carer status, recipient, disability status, age, sex
- Table_31.1 - Carer status, by geographic location, age, sex
- Table_32.1 - 15-.. yo, carer status, sex 
- Table_33.1 - Employed 15-64 yo, carer status, sex 
- Table_34.1 - Primary Carer, recipient, age, sex
- Table_35.1 - Carer and recipient living in or other households, age
- Table_36.1 - Primary Carer, Time spending in care, sex  ****
- Table_37.1 - Primary Carer, age, time spending in care, disability status, ***** 
- Table_38.1 - Primary Carer, time spending in care, select recipint   ****
- Table_39.1 - Primary Carer, reason for taking a carer, sex   ****
- Table_40.1 - Primary Carer, reason for taking a carer, age of recipient ****
- Table_41.1 - Primary Carer, satisfaction of service recieved, sex, age  ****
- Table_42.1 - Primary Carer, social community participation with recipient, time spending in car, age  ****
- Table_43.1 - Primary Carer, social community participation without recipient, time spending in car, age  ****

In [1]:
# Import Packages
import pandas as pd
import itertools
# import re

In [2]:
# Set option to display all columns
pd.set_option('display.max_columns', None)

## 1. Read in Raw Data from a XLS file

In [3]:
# Function for reading in raw data from a XLS file
def read_in_data(file_path, sheet_name):
    """
    Function for reading in raw data from XLS file.
    Inputs: 
        - file_path, type: string, desc: XLS file path
        - sheet_name, type: string, desc: Sheet Name
    Outputs:
        - raw_data, type: dataframe, desc: Raw data
    """

    raw_data = pd.read_excel(io=file_path, sheet_name=sheet_name)
    
    return raw_data

In [4]:
# Read in data
filepath_raw_data = 'DataBases/44300do030.xls'
sheet_name = 'Table_34.1'
df_raw_carer_34 = read_in_data(filepath_raw_data, sheet_name)

In [5]:
# Check how the dataframe looks like
df_raw_carer_34

,Australian Bureau of Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,"44300DO030_2018 Disability, Ageing and Carers,...",NaN,NaN,NaN,NaN,NaN
1,Released at 11.30am (Canberra time) Thurs 24 O...,NaN,NaN,NaN,NaN,NaN
2,"Table 34.1 Primary carers, relationship of car...",NaN,NaN,NaN,NaN,NaN
3,NaN,Relationship of carer to main recipient of care,NaN,NaN,NaN,NaN
4,NaN,Partner of recipient,Child of recipient,Parent of recipient,Other relationship to recipient,Total
5,ESTIMATE ('000),NaN,NaN,NaN,NaN,NaN
6,Male primary carers,NaN,NaN,NaN,NaN,NaN
7,15–24 years,0,4.4,0,0,7
8,25–44 years,11.8,17.6,6.4,3.8,39
9,45–64 years,46.2,36.6,15.8,11.4,108.2
10,65 years and over,73.4,6.1,5.2,6.4,89.4
11,Total,129.6,62.7,27.1,22.1,241.9
12,NaN,NaN,NaN,NaN,NaN,NaN
13,Female primary carers,NaN,NaN,NaN,NaN,NaN
14,15–24 years,1.3,2.4,1.2,8,13.7
15,25–44 years,20.7,31.5,99.8,16.9,165.6
16,45–64 years,64.2,110.8,88.3,34.4,298.2
17,65 years and over,99,15.6,18.1,7.7,139.3
18,Total,185.7,161.4,205.6,65.2,618.8
19,NaN,NaN,NaN,NaN,NaN,NaN
20,All primary carers,NaN,NaN,NaN,NaN,NaN
21,15–24 years,1.3,7.8,1.9,8.1,18.6
22,25–44 years,32,48.6,104,20.5,205.6
23,45–64 years,111.4,146.6,102.2,45.7,406
24,65 years and over,172.8,20.3,21.8,12.1,228.3
25,Total,315.2,226,233.5,89.6,861.6
26,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN
28,© Commonwealth of Australia 2019,NaN,NaN,NaN,NaN,NaN

## 2. Clean up Raw Data

In [6]:
# Drop useless rows and columns
col_names = df_raw_carer_34.iloc[4,:]
df_carer_34 = df_raw_carer_34.copy()
df_carer_34.drop(labels=[0,1,2,3,5,6,12,13,19,20,26,27,28], axis=0, inplace=True)
df_carer_34.reset_index(drop=True, inplace=True)
df_carer_34.columns = col_names
df_carer_34.rename(columns={'Total ':'total'}, inplace=True)
df_carer_34.columns.names = ['']
df_carer_34

,NaN,Partner of recipient,Child of recipient,Parent of recipient,Other relationship to recipient,total
0,NaN,Partner of recipient,Child of recipient,Parent of recipient,Other relationship to recipient,Total
1,15–24 years,0,4.4,0,0,7
2,25–44 years,11.8,17.6,6.4,3.8,39
3,45–64 years,46.2,36.6,15.8,11.4,108.2
4,65 years and over,73.4,6.1,5.2,6.4,89.4
5,Total,129.6,62.7,27.1,22.1,241.9
6,15–24 years,1.3,2.4,1.2,8,13.7
7,25–44 years,20.7,31.5,99.8,16.9,165.6
8,45–64 years,64.2,110.8,88.3,34.4,298.2
9,65 years and over,99,15.6,18.1,7.7,139.3
10,Total,185.7,161.4,205.6,65.2,618.8
11,15–24 years,1.3,7.8,1.9,8.1,18.6
12,25–44 years,32,48.6,104,20.5,205.6
13,45–64 years,111.4,146.6,102.2,45.7,406
14,65 years and over,172.8,20.3,21.8,12.1,228.3
15,Total,315.2,226,233.5,89.6,861.6

In [7]:
# Reset index and prepare for adding multiindex (in column)
df_carer_34.rename(columns={df_carer_34.columns[0]:'Index'}, inplace=True)
df_carer_34.set_index(keys='Index', drop=True, inplace=True)
df_carer_34

,Partner of recipient,Child of recipient,Parent of recipient,Other relationship to recipient,total
Index,,,,,
NaN,Partner of recipient,Child of recipient,Parent of recipient,Other relationship to recipient,Total
15–24 years,0,4.4,0,0,7
25–44 years,11.8,17.6,6.4,3.8,39
45–64 years,46.2,36.6,15.8,11.4,108.2
65 years and over,73.4,6.1,5.2,6.4,89.4
Total,129.6,62.7,27.1,22.1,241.9
15–24 years,1.3,2.4,1.2,8,13.7
25–44 years,20.7,31.5,99.8,16.9,165.6
45–64 years,64.2,110.8,88.3,34.4,298.2
65 years and over,99,15.6,18.1,7.7,139.3
Total,185.7,161.4,205.6,65.2,618.8
15–24 years,1.3,7.8,1.9,8.1,18.6
25–44 years,32,48.6,104,20.5,205.6
45–64 years,111.4,146.6,102.2,45.7,406
65 years and over,172.8,20.3,21.8,12.1,228.3
Total,315.2,226,233.5,89.6,861.6

In [8]:
# Adding multiIndex (in index)
first_level = ['Relationship of carer to main recipient of care', 'total']
second_level = list(col_names)[1:-1]
levels_1_1 = list(itertools.product([first_level[0]], second_level[0:4]))
levels_1_2 = list(itertools.product([first_level[1]], ['total']))
levels = levels_1_1 + levels_1_2
df_carer_34.columns = pd.MultiIndex.from_tuples(levels, names=["Relation", "Type"])
df_carer_34.reset_index(inplace=True)
df_carer_34

Relation              Index Relationship of carer to main recipient of care  \
Type                                                   Partner of recipient
0                       NaN                            Partner of recipient
1               15–24 years                                               0
2               25–44 years                                            11.8
3               45–64 years                                            46.2
4         65 years and over                                            73.4
5                     Total                                           129.6
6               15–24 years                                             1.3
7               25–44 years                                            20.7
8               45–64 years                                            64.2
9         65 years and over                                              99
10                    Total                                           185.7
11              15–24 years                                             1.3
12              25–44 years                                              32
13              45–64 years                                           111.4
14        65 years and over                                           172.8
15                    Total                                           315.2

Relation                                           \
Type      Child of recipient  Parent of recipient
0         Child of recipient  Parent of recipient
1                        4.4                    0
2                       17.6                  6.4
3                       36.6                 15.8
4                        6.1                  5.2
5                       62.7                 27.1
6                        2.4                  1.2
7                       31.5                 99.8
8                      110.8                 88.3
9                       15.6                 18.1
10                     161.4                205.6
11                       7.8                  1.9
12                      48.6                  104
13                     146.6                102.2
14                      20.3                 21.8
15                       226                233.5

Relation                                    total
Type      Other relationship to recipient   total
0         Other relationship to recipient  Total
1                                       0       7
2                                     3.8      39
3                                    11.4   108.2
4                                     6.4    89.4
5                                    22.1   241.9
6                                       8    13.7
7                                    16.9   165.6
8                                    34.4   298.2
9                                     7.7   139.3
10                                   65.2   618.8
11                                    8.1    18.6
12                                   20.5   205.6
13                                   45.7     406
14                                   12.1   228.3
15                                   89.6   861.6

In [9]:
# Adding multiIndex (in column)
df_carer_34.reset_index(inplace=True, drop=True)
df_carer_34

Relation              Index Relationship of carer to main recipient of care  \
Type                                                   Partner of recipient
0                       NaN                            Partner of recipient
1               15–24 years                                               0
2               25–44 years                                            11.8
3               45–64 years                                            46.2
4         65 years and over                                            73.4
5                     Total                                           129.6
6               15–24 years                                             1.3
7               25–44 years                                            20.7
8               45–64 years                                            64.2
9         65 years and over                                              99
10                    Total                                           185.7
11              15–24 years                                             1.3
12              25–44 years                                              32
13              45–64 years                                           111.4
14        65 years and over                                           172.8
15                    Total                                           315.2

Relation                                           \
Type      Child of recipient  Parent of recipient
0         Child of recipient  Parent of recipient
1                        4.4                    0
2                       17.6                  6.4
3                       36.6                 15.8
4                        6.1                  5.2
5                       62.7                 27.1
6                        2.4                  1.2
7                       31.5                 99.8
8                      110.8                 88.3
9                       15.6                 18.1
10                     161.4                205.6
11                       7.8                  1.9
12                      48.6                  104
13                     146.6                102.2
14                      20.3                 21.8
15                       226                233.5

Relation                                    total
Type      Other relationship to recipient   total
0         Other relationship to recipient  Total
1                                       0       7
2                                     3.8      39
3                                    11.4   108.2
4                                     6.4    89.4
5                                    22.1   241.9
6                                       8    13.7
7                                    16.9   165.6
8                                    34.4   298.2
9                                     7.7   139.3
10                                   65.2   618.8
11                                    8.1    18.6
12                                   20.5   205.6
13                                   45.7     406
14                                   12.1   228.3
15                                   89.6   861.6

In [10]:
# Dropping useless rows
df_carer_34_1 =df_carer_34.copy()
df_carer_34_1.drop(labels=[0] , axis=0, inplace=True)
df_carer_34_1.reset_index(drop=True, inplace=True)
df_carer_34_1

Relation              Index Relationship of carer to main recipient of care  \
Type                                                   Partner of recipient
0               15–24 years                                               0
1               25–44 years                                            11.8
2               45–64 years                                            46.2
3         65 years and over                                            73.4
4                     Total                                           129.6
5               15–24 years                                             1.3
6               25–44 years                                            20.7
7               45–64 years                                            64.2
8         65 years and over                                              99
9                     Total                                           185.7
10              15–24 years                                             1.3
11              25–44 years                                              32
12              45–64 years                                           111.4
13        65 years and over                                           172.8
14                    Total                                           315.2

Relation                                         \
Type     Child of recipient Parent of recipient
0                       4.4                   0
1                      17.6                 6.4
2                      36.6                15.8
3                       6.1                 5.2
4                      62.7                27.1
5                       2.4                 1.2
6                      31.5                99.8
7                     110.8                88.3
8                      15.6                18.1
9                     161.4               205.6
10                      7.8                 1.9
11                     48.6                 104
12                    146.6               102.2
13                     20.3                21.8
14                      226               233.5

Relation                                  total
Type     Other relationship to recipient  total
0                                      0      7
1                                    3.8     39
2                                   11.4  108.2
3                                    6.4   89.4
4                                   22.1  241.9
5                                      8   13.7
6                                   16.9  165.6
7                                   34.4  298.2
8                                    7.7  139.3
9                                   65.2  618.8
10                                   8.1   18.6
11                                  20.5  205.6
12                                  45.7    406
13                                  12.1  228.3
14                                  89.6  861.6

In [11]:
levels_names = df_carer_34_1['Index'].unique()
levels_names

array(['15–24 years', '25–44 years', '45–64 years', '65 years and over',
       'Total'], dtype=object)

In [12]:
first_level = ['Male primary carers', 'Female primary carers', 'All primary carers']
first_level

['Male primary carers', 'Female primary carers', 'All primary carers']

In [13]:
second_level = levels_names
second_level

array(['15–24 years', '25–44 years', '45–64 years', '65 years and over',
       'Total'], dtype=object)

In [14]:
# Adding multiIndex (in index)
levels_all = list(itertools.product(first_level, second_level))
multi_index = pd.MultiIndex.from_tuples(levels_all, names=['Gender', 'Age'])
df_carer_34_1.set_index(keys=multi_index, drop=True, inplace=True)
df_carer_34_1.drop(columns='Index', axis=1, inplace=True)
df_carer_34_1

C:\Users\Henry\anaconda3\lib\site-packages\pandas\core\generic.py:4153: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)

Relation                                Relationship of carer to main recipient of care  \
Type                                                               Partner of recipient
Gender                Age
Male primary carers   15–24 years                                                     0
                      25–44 years                                                  11.8
                      45–64 years                                                  46.2
                      65 years and over                                            73.4
                      Total                                                       129.6
Female primary carers 15–24 years                                                   1.3
                      25–44 years                                                  20.7
                      45–64 years                                                  64.2
                      65 years and over                                              99
                      Total                                                       185.7
All primary carers    15–24 years                                                   1.3
                      25–44 years                                                    32
                      45–64 years                                                 111.4
                      65 years and over                                           172.8
                      Total                                                       315.2

Relation                                                    \
Type                                    Child of recipient
Gender                Age
Male primary carers   15–24 years                      4.4
                      25–44 years                     17.6
                      45–64 years                     36.6
                      65 years and over                6.1
                      Total                           62.7
Female primary carers 15–24 years                      2.4
                      25–44 years                     31.5
                      45–64 years                    110.8
                      65 years and over               15.6
                      Total                          161.4
All primary carers    15–24 years                      7.8
                      25–44 years                     48.6
                      45–64 years                    146.6
                      65 years and over               20.3
                      Total                            226

Relation                                                     \
Type                                    Parent of recipient
Gender                Age
Male primary carers   15–24 years                         0
                      25–44 years                       6.4
                      45–64 years                      15.8
                      65 years and over                 5.2
                      Total                            27.1
Female primary carers 15–24 years                       1.2
                      25–44 years                      99.8
                      45–64 years                      88.3
                      65 years and over                18.1
                      Total                           205.6
All primary carers    15–24 years                       1.9
                      25–44 years                       104
                      45–64 years                     102.2
                      65 years and over                21.8
                      Total                           233.5

Relation                                                                 total
Type                                    Other relationship to recipient  total
Gender                Age
Male primary carers   15–24 years                                     0      7
                      25–44 years                                   3.8     39
                      45–64 years                                  11.4  108.2
                      65 years and over                             6.4   89.4
                      Total                                        22.1  241.9
Female primary carers 15–24 years                                     8   13.7
                      25–44 years                                  16.9  165.6
                      45–64 years                                  34.4  298.2
                      65 years and over                             7.7  139.3
                      Total                                        65.2  618.8
All primary carers    15–24 years                                   8.1   18.6
                      25–44 years                                  20.5  205.6
                      45–64 years                                  45.7    406
                      65 years and over                            12.1  228.3
                      Total                                        89.6  861.6

## 3. Export Clean Data to a CSV file

In [15]:
# Export full version
df_carer_34_1.to_csv('Output\EPIC4_T34_1_V1.csv', index=True)